# Generated by Django 2.2.4 on 2019-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('checkin_count', models.IntegerField(blank=True, null=True)),
                ('ticket_count', models.IntegerField(blank=True, null=True)),
                ('session_count', models.IntegerField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
